apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs1
spec:
 replicas: 3
 selector:
   matchLabels:
     app: nodejs-app1
 template:
   metadata:
     labels:
       app: nodejs-app1
   spec:                  
     containers:
     - name: nodejs-app1
       image: vigneshvicky12345/node-app:latest
       ports:
       - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-service1
spec:
  type: LoadBalancer
  selector:
    app: nodejs-app1
  ports:
    - port: 80
      targetPort: 3000
